# Generated by Django 6.0.1 on 2026-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_refund_delete_refundrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='processed_at',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='expected_refund_date',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='refund',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='expected_paid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='expected_paid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='provider',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
    ]
