# Generated by Django 6.0.1 on 2026-02-07 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_event_alter_order_commission_amount_and_more'),
        ('payments', '0003_payment_reference_id_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('momo', 'MTN MoMo'), ('mgurush', 'M-Gurush')], max_length=20),
        ),
    ]
