# Generated by Django 6.0.1 on 2026-02-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('nightlife', 'Nightlife'), ('comedy', 'Comedy'), ('liveband', 'Lifeband'), ('culture', 'Culture'), ('conference', 'Conference'), ('other', 'Other')], default='music', max_length=20),
        ),
    ]
