# Generated by Django 6.0.1 on 2026-02-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payout_done',
            field=models.BooleanField(default=False),
        ),
    ]
