# Generated by Django 6.0.1 on 2026-02-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_customer_user_is_organizer_organizerrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizerrequest',
            old_name='business_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='organizerrequest',
            name='location',
        ),
        migrations.RemoveField(
            model_name='organizerrequest',
            name='phone',
        ),
        migrations.AddField(
            model_name='organizerrequest',
            name='id_document',
            field=models.FileField(default='', upload_to='organizer_ids/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizerrequest',
            name='momo_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
