# Generated by Django 6.0.1 on 2026-02-27 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_phone', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizers/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='organizers/banners/')),
                ('payout_provider', models.CharField(choices=[('momo', 'MTN MoMo'), ('mgurush', 'M-Gurush')], default='momo', max_length=20)),
                ('payout_phone', models.CharField(blank=True, max_length=30)),
                ('auto_payout', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
