# Generated by Django 6.0.1 on 2026-02-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='reference',
        ),
    ]
