# Generated by Django 6.0.1 on 2026-02-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_payout_failure_reason_payout_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
    ]
