# Generated by Django 6.0.1 on 2026-02-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_withdrawn'),
        ('payouts', '0004_payout_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='linked_payouts', to='orders.order'),
        ),
    ]
