# Generated by Django 6.0.1 on 2026-02-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_event_remove_ticket_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets_qr/'),
        ),
    ]
