# Generated by Django 6.0.1 on 2026-02-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/qr_codes/'),
        ),
    ]
