# Generated by Django 6.0.1 on 2026-02-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
