# Generated by Django 6.0.1 on 2026-02-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_financial_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
