# Generated by Django 6.0.1 on 2026-02-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_commission_amount_alter_order_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.AlterField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='organizer_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
